'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomerOverview
    
    '''<summary>
    '''displayCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents displayCustomers As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''grdvCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdvCustomers As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''displayCustomersWithOpenTickets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents displayCustomersWithOpenTickets As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''grdvCustomersTicketsOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdvCustomersTicketsOpen As Global.System.Web.UI.WebControls.GridView
End Class
