'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewTicket
    
    '''<summary>
    '''lblTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicket As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSiteAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOpenedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpenedDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtJobStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAssignedTech control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssignedTech As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTechCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTechCell As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlJobType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJobType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPriority As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtJobDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobDesc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnUpdateTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateTicket As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnDeleteTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteTicket As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.LinkButton
End Class
